<?	$this->view->set_css('public/css/chatbox.css');	$this->view->set_js('public/js/chatbox.js');	$this->view->display('includes/header');?>
	<div id="trollbox">
		<h1 style="text-align: center; margin-bottom: 50px;">Chatbox</h1>
		<div id="chatbox_text_container">
		</div>
		<div id="chatbox_text_input">
			<textarea cols="1" rows="1"></textarea>
		</div>
	</div>

<? $this->view->display('includes/footer'); ?>