<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Login</title>
		<meta name="description" content="description" />
		<meta name="keywords" content="keywords" />
		<link rel="stylesheet" href="<?= ROOT_URL; ?>design/admin/css/login.css" />
		<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<form id="loginForm" name="loginForm" action="" method="post">
			<input type="hidden" name="action" value="login" />
			<div id="login">
				<div id="top">Login Form</div>
				<div id="fields">
					<input id="username" name="username" type="text" class="text" />
					<input id="password" name="password" type="password" class="text" />
				</div>
				<div id="bottom"><input id="submit" name="submit" type="submit" value="Login" /></div>
			</div>
			<? if ($result && $result['error'] == 1 && $result['message']) { ?> 
			<div id="red"><?= htmlspecialchars($result['message']); ?></div>
			<? } ?>
		</form>
	</body>
</html>